@startuml
left to right direction

package "Resume Builder System" {
  package "Models" #LightGreen {
    [User]
    [Resume]
    [SpecificResume]
    [Template]
  }

  package "Services" #LightBlue {
    [AnonymousAuthService]
    [OAuthService]
    [ResumeService]
    [TemplateService]
    [AIService]  
  }

  package "Controllers" #LightPink {
    [AuthController]
    [ResumeController]
    [TemplateController]
  }

  package "Repositories" #Khaki {
    [UserRepository]
    [ResumeRepository]
    [SpecificResumeRepository]
    [TemplateRepository]
  }

  package "Utils" #Plum {
    [DocumentParser]
    [LatexRenderer]
    [FileStorage]
  }

  package "Configuration" #LightCyan {
    [SpringBootApplication]
    [AWSLambdaConfig]
  }

  package "AWS Integration" #Moccasin {
    [S3Storage]
    [LambdaHandler]
  }

  package "External IA Integration" #Lavender {
    [Gemini]
  }
}

' Relacionamentos
[AnonymousAuthService] -[#Blue]-> [UserRepository]
[AuthController] -[#Red]-> [AnonymousAuthService] : "Login/Registro anônimo"
[AuthController] -[#Red]-> [OAuthService] : "Login/Registro usando OAuth"
[DocumentParser] -[#DarkViolet]-> [ResumeService]
[FileStorage] -[#DarkViolet]-> [S3Storage] : "usa"
[LambdaHandler] -[#Orange]-> [SpringBootApplication] : "Envia eventos"
[LatexRenderer] -[#DarkViolet]-> [ResumeService] 
[OAuthService] -[#Blue]-> [UserRepository]
[ResumeController] -[#Red]-> [ResumeService] : "Gerencia currículo"
[ResumeService] -[#Blue]-> [DocumentParser]
[ResumeService] -[#Blue]-> [FileStorage] : "Grava arquivo PDF" 
[ResumeService] -[#Blue]-> [LatexRenderer]
[ResumeService] -[#Blue]-> [ResumeRepository]
[ResumeService] -[#Blue]-> [SpecificResumeRepository]
[ResumeService] -[#Blue]-> [TemplateService] : "Carrega Template"
[ResumeService] -[#Blue]-> [AIService] : "Sugestões e análise da IA"
[AIService] -[#MediumPurple]-> [Gemini] : "Chama Google Gemini API"
[SpringBootApplication] -[#Cyan]-> [AWSLambdaConfig] : "Configura"    
[TemplateController] -[#Red]-> [TemplateService] : "Escolhe template"
[TemplateService] -[#Blue]-> [TemplateRepository] 
[User] "1" -[#Green]-> "0..1" [SpecificResume] : "possui um para cada vaga"
[User] "1" -[#Green]-> "1" [Resume] : "tem"

@enduml