' This is part of the documentation of Deployo.io Resume Builder System.
' Copyright (C) 2025
' Leila Otto Algarve
' Licensed under the GNU Free Documentation License v1.3 or later.
' See LICENSE-DOCUMENTATION for details. 
@startuml
package "Models" #LightGreen {
  class User {
    -id: String
    -trialCode: String
    -oauthToken: String
    -createdAt: DateTime
  }

  class Resume {
    -id: String
    -userId: String
    -rawData: String
    -parsedData: Json
    -templateId: String
    -styles: Json
    -pdfUrl: String
    -createdAt: DateTime
  }

  class SpecificResume {
    -id: String
    -jobDescription: String
    -customData: Json
    -templateId: String
    -pdfUrl: String
    -createdAt: DateTime
  }
  
note right of SpecificResume
	Currículo otimizado com a ajuda de uma IA 
	para uma descrição de vaga específica. Ele 
	é criado com base no currículo atual do usuário. 
	Alterações posteriores no currículo do usuário 
	não o afetam.
endnote  

  class Template {
    -id: String
    -name: String
    -templateURL: String 
  }
}

note right of Template::templateURL
    Campo que aponta para
    os arquivos de definição
    do modelo que
    foi instalado no sistema.
endnote
	

' Relacionamentos
User "1" -- "1" Resume : "possui"
User "1" -- "0..*" SpecificResume : "possui um para cada vaga"
SpecificResume "1" -- "1" Template : "usa"
Resume "1" -- "1" Template : "padrão"

@enduml
